---
- hosts: all

  become: yes
  become_user: root
  remote_user: deploy

  vars:
    apt_packages:
      - fail2ban
      - git
      - htop
      - sudo
      - ufw
      - vim

  tasks:
    # Install packages
    - name: Update the system
      apt:
        update_cache: yes
        upgrade: safe
    - name: Install pip
      apt:
        name:
          - build-essential
          - python-dev
          - python-pip
    - name: Upgrade pip
      pip:
        name: pip
        state: latest
    - name: Enable SNI suppport in Python 2.7.6
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - ndg-httpsclient
        - pyasn1
        - pyopenssl
        - urllib3
    - name: Install apt packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items: "{{ apt_packages }}"

    # Secure the system
    - name: Set up a firewall
      ufw:
        policy: deny
        state: enabled
    - name: Allow SSH connections
      ufw:
        port: 22
        proto: tcp
        rule: allow
    - name: Allow HTTP connections
      ufw:
        port: 80
        proto: tcp
        rule: allow
    - name: Disable root SSH login
      lineinfile:
        dest: /etc/ssh/sshd_config
        line: PermitRootLogin no
        regexp: ^PermitRootLogin
      notify: Restart SSH

    - name: Install TensorFlow
      pip:
        name: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl
        state: latest

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
